  export const cuisineList = [
    'مش',
    'Ful Medames',
    'جبنة قديمة',
    'Taameya',
    'Hawawshi',
    'Fattah',
    'Mahshi',
    'Basbousa',
    'Kunafa',
    'Umm Ali',
    'Shawarma',
    'Kebab',
    'Kofta',
    'Ringa',
    'Feseekh',
    'Besarah',
    'Roz Bel Laban',
    'Qolqas',
    'Sabanekh',
    'Bamya',
    'Aish Baladi',
    'Aish Merahrah',
    'Halawa',
    'Rozz Meammar',
    'Kibda Iskandrani',
    'Moussaka'
  ];
